### ISSUE TITLE
Currency issue

### ISSUE THREAD

**Issue by quanghd** [uber/rides-ios-sdk#119]
Hi, I'm Vietnamese developer.

When I requested this API:

https://developer.uber.com/docs/rides/api/v1-estimates-price

It returned different unit for _estimate, high_estimate, low_estimate_ values:

{
    prices =     (
                {
            "currency_code" = VND;
            "display_name" = uberMOTO;
            distance = "1.18";
            duration = 360;
            estimate = "10.000\U00a0\U20ab";
            "high_estimate" = 10;
            "localized_display_name" = uberMOTO;
            "low_estimate" = 10;
            minimum = 10000;
            "product_id" = "9988f406-d98b-48eb-a4b7-a1645fa78e8e";
            "surge_multiplier" = 1;
        },
                {
            "currency_code" = VND;
            "display_name" = uberX;
            distance = "1.18";
            duration = 360;
            estimate = "15.171-18.616\U00a0\U20ab";
            "high_estimate" = 18;
            "localized_display_name" = uberX;
            "low_estimate" = 15;
            minimum = 5000;
            "product_id" = "4e6b60d5-8e3a-4772-86b5-324d09b0ce39";
            "surge_multiplier" = 1;
        },
                {
            "currency_code" = VND;
            "display_name" = UberBLACK;
            distance = "1.18";
            duration = 360;
            estimate = "25.751-32.771\U00a0\U20ab";
            "high_estimate" = 32;
            "localized_display_name" = UberBLACK;
            "low_estimate" = 25;
            minimum = 5000;
            "product_id" = "995a3c4a-fd8b-4a99-92f7-bb341b0addc6";
            "surge_multiplier" = 1;
        },
                {
            "currency_code" = VND;
            "display_name" = SUV;
            distance = "1.18";
            duration = 360;
            estimate = "25.751-32.771\U00a0\U20ab";
            "high_estimate" = 32;
            "localized_display_name" = SUV;
            "low_estimate" = 25;
            minimum = 5000;
            "product_id" = "9da8622e-e084-4a53-96d1-e510c4838b56";
            "surge_multiplier" = 1;
        }
    );
}

The values in "estimate" field is correct, the values in high_estimate and low_estimate must be multiplied by 1000.

Please fix it soon.

**Comment by arogal** [comment]
Hi quanghd,

This is actually working as intended. I believe you are confused because are not localizing the money field using , instead of . for decimals. 

To support this, the library would need to allow the Accept-Language to be passed. This issue can be used to track that.

**Comment by quanghd** [comment]
Hi, I meant the "low_estimate" returned is 25 VND instead for 25000 VND. Do you think It has any problem in parsing the response?

**Comment by arogal** [comment]
I see what you mean now. We'll investigate and report back.

**Comment by quanghd** [comment]
Hi guy, any update?

**Comment by arogal** [comment]
We are still investigating a fix. In the meantime, would it be possible for
you to make the fix client side? We can assist with any code to help.

**Comment by quanghd** [comment]
Yes, we can. But we're not sure that this issue is just happening in Vietnam currency. How about other countries with local currency?

**Comment by arogal** [comment]
Currently, we are only seeing this for very specific cases of localization
and amounts. We are actively working on a fix, so appreciate your patience.

**Comment by oancius** [comment]
it could be because the dot is interpreted as decimal point instead of thousands point for some region formats?

**Comment by quanghd** [comment]
@oancius You might be right, so can we change the way JSON parser read these values?

**Comment by arogal** [comment]
Yes, this is similar the bug we are encountering server side.

**Comment by quanghd** [comment]
@arogal Can you just return float format for these values?

**Comment by arogal** [comment]
They are actually floats. The change is a bit more complicated than that,
but something we are working on.

**Comment by quanghd** [comment]
Thank you, waiting for the update...

**Comment by arogal** [comment]
We are continuing to work on this, but should have a fix out later this
week.

**Comment by futuretap** [comment]
I can reproduce the same issue for Bogota, Colombia (estimate: "4600.300-13.000 $"):

```
{
  "prices": [
    {
      "currency_code": "COP", 
      "display_name": "uberPOOL", 
      "distance": 6.99, 
      "duration": 1560, 
      "estimate": "8.800\u00a0COP", 
      "high_estimate": 8801, 
      "localized_display_name": "uberPOOL", 
      "low_estimate": 8800, 
      "minimum": null, 
      "product_id": "6d09e374-d9ec-4803-ba44-35a47d1be60c", 
      "surge_multiplier": 1.0
    }, 
    {
      "currency_code": "COP", 
      "display_name": "uberX", 
      "distance": 6.99, 
      "duration": 1560, 
      "estimate": "4600.300-13.000\u00a0$", 
      "high_estimate": 13, 
      "localized_display_name": "uberX", 
      "low_estimate": 4600, 
      "minimum": 4600, 
      "product_id": "4081c16d-672e-41b6-abb3-65ffe5a2f1ab", 
      "surge_multiplier": 1.0
    }, 
    {
      "currency_code": "COP", 
      "display_name": "Uber", 
      "distance": 6.99, 
      "duration": 1560, 
      "estimate": "6000.800-21.500\u00a0$", 
      "high_estimate": 21, 
      "localized_display_name": "Uber", 
      "low_estimate": 6000, 
      "minimum": 6000, 
      "product_id": "83e16d10-8018-4ca9-b4bb-6e1c381baa11", 
      "surge_multiplier": 1.0
    }, 
    {
      "currency_code": "COP", 
      "display_name": "UberVAN", 
      "distance": 6.99, 
      "duration": 1560, 
      "estimate": "9000.600-31.200\u00a0$", 
      "high_estimate": 31, 
      "localized_display_name": "UberVAN", 
      "low_estimate": 9000, 
      "minimum": 9000, 
      "product_id": "573b4a48-c1d5-4b04-b21d-66d5524cd6b9", 
      "surge_multiplier": 1.0
    }, 
    {
      "currency_code": "COP", 
      "display_name": "Bici", 
      "distance": 6.99, 
      "duration": 1560, 
      "estimate": "8000.800-23.500\u00a0$", 
      "high_estimate": 23, 
      "localized_display_name": "Bici", 
      "low_estimate": 8000, 
      "minimum": 8000, 
      "product_id": "d6b8adb8-9b4d-44a9-a590-3ef81a999f90", 
      "surge_multiplier": 1.0
    }
  ]
}

```

**Comment by arogal** [comment]
Thanks for the report. We are continuing to work on a fix and will let you
know when it's launched. Thanks!

**Comment by arogal** [comment]
This should now be resolved. Please reopen if you continue to see this issue. Thanks again for reporting this!

**Comment by futuretap** [comment]
Looks like this is not yet resolved. Try this call for Bogota, Colombia: `GET /v1/estimates/price?start_latitude=4.6334251&start_longitude=-74.1699111&end_latitude=4.5457653&end_longitude=-74.126932`. The estimate is displayed as `COP 10.620-12981` for uberPOOL and `13.300-16.800 $` for uberX. It should be consistent in currency and decimal separator.

```
{
  "prices": [
    {
      "localized_display_name": "uberPOOL",
      "distance": 8.64,
      "display_name": "uberPOOL",
      "product_id": "6d09e374-d9ec-4803-ba44-35a47d1be60c",
      "high_estimate": 12982,
      "surge_multiplier": 1.0,
      "minimum": null,
      "low_estimate": 10620,
      "duration": 2220,
      "estimate": "COP\u00a010.620-12981",
      "currency_code": "COP"
    },
    {
      "localized_display_name": "uberX",
      "distance": 8.64,
      "display_name": "uberX",
      "product_id": "4081c16d-672e-41b6-abb3-65ffe5a2f1ab",
      "high_estimate": 16800,
      "surge_multiplier": 1.0,
      "minimum": 4600,
      "low_estimate": 13300,
      "duration": 2220,
      "estimate": "13.300-16.800\u00a0$",
      "currency_code": "COP"
    },
    {
      "localized_display_name": "Uber",
      "distance": 8.64,
      "display_name": "Uber",
      "product_id": "83e16d10-8018-4ca9-b4bb-6e1c381baa11",
      "high_estimate": 27400,
      "surge_multiplier": 1.0,
      "minimum": 6000,
      "low_estimate": 21400,
      "duration": 2220,
      "estimate": "21.400-27.400\u00a0$",
      "currency_code": "COP"
    },
    {
      "localized_display_name": "UberVAN",
      "distance": 8.64,
      "display_name": "UberVAN",
      "product_id": "573b4a48-c1d5-4b04-b21d-66d5524cd6b9",
      "high_estimate": 39500,
      "surge_multiplier": 1.0,
      "minimum": 9000,
      "low_estimate": 31000,
      "duration": 2220,
      "estimate": "31.000-39.500\u00a0$",
      "currency_code": "COP"
    },
    {
      "localized_display_name": "Bici",
      "distance": 8.64,
      "display_name": "Bici",
      "product_id": "d6b8adb8-9b4d-44a9-a590-3ef81a999f90",
      "high_estimate": 29400,
      "surge_multiplier": 1.0,
      "minimum": 8000,
      "low_estimate": 23400,
      "duration": 2220,
      "estimate": "23.400-29.400\u00a0$",
      "currency_code": "COP"
    }
  ]
}
```

**Comment by arogal** [comment]
Thanks futuretap. This looks to be a separate issue, though something that should also be fixed.
